version: "3.8"

services:
  anaconda3:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: jupyter-all
    image: registry.cn-shanghai.aliyuncs.com/onekr/jupyter-all:latest
    tty: true
    ports:
        - 8888:8888
    volumes:
        - ./notebooks:/opt/notebooks